#雷电是否会造成火焰
LightningFire: true

# 以下伤害 0为0伤害 但还是会触发事件
# 如果是false 就是代表不但没伤害 而且还不会触发事件
# 如果下面需要用到哪个 把注释取消就好  参考下面的凋零伤害
# 更新: 1:true   为真伤 1点,免疫护甲之类的   真伤请不要超过服务器的最高血量
# 4月10日更新:  最高血量百分比   0.01% 为最高血量的百分之一的伤害 实际造成伤害=四舍五入


# #枯萎\凋零伤害
WITHER: 1
# #方块窒息造成的伤害
SUFFOCATION: 1:true
# #飞行撞到墙上的伤害 (?滑翔翼撞墙吗? (谨慎修改
FLY_INTO_WALL: 0.01%
# #当实体攻击另外一个实体时 造成的伤害 (谨慎修改
# ENTITY_ATTACK: false
# #当横扫之刃到另外一个实体时 造成的伤害 (谨慎修改
# ENTITY_SWEEP_ATTACK: 1
# #当受到弹射物时造成的伤害 (谨慎修改
# PROJECTILE: 1
# #方块爆炸时 造成的伤害 (TNT?  (谨慎修改
# BLOCK_EXPLOSION: 1
# #实体爆炸 造成的伤害 (苦力怕? (谨慎修改
# ENTITY_EXPLOSION: 1
# #被直接伤害型药水喷溅到的伤害  (谨慎修改
# MAGIC: 1
# #被掉落的方块砸中造成的伤害  (谨慎修改
# FALLING_BLOCK: 1
# #当生物接触仙人掌时造成的伤害
# CONTACT: 1
# #掉落伤害 伤害为 掉落高度-3
# FALL: 1
# #火焰方块 造成的伤害
# FIRE: 1
# #身上着火 造成的伤害
# FIRE_TICK: 1
# #雪人融化 每秒受到的伤害
# MELTING: 1
# #身在岩浆里的伤害(裸露
# LAVA: 4
# #水里窒息伤害
# DROWNING: 2
# #掉进虚空里的伤害
# VOID: 4
# #被闪电击中的伤害
# LIGHTNING: 5
# #使用指令 /kill 造成的伤害
# SUICIDE: 1000
# #饥饿造成的伤害
# STARVATION: 1
# #被持续的 伤害药水造成的伤害
# POISON: 1
# #荆棘造成的反伤 (一件衣服默认 = 1
# THORNS: 1
# #龙息造成的伤害
# DRAGON_BREATH: 1
# #踩到岩浆块造成的伤害
# HOT_FLOOR: 1
# #生物挤压造成的伤害
# CRAMMING: 6
# #干涸 本应在水里的生物 不在水里 受到的伤害
# DRYOUT: 1